### ISSUE TITLE
Configurable window of "Last N Hours" of segments to keep

### ISSUE THREAD

**Issue by ekimekim** [ekimekim/wubloader#110]
To minimize disk requirements on "just in case" capture nodes, we want to configure them to only keep, say, the last 24 hours of data.

This requires two features:
* Able to configure backfiller to only backfill up to N hours ago
* Some component (this could probably also be backfiller) to delete expired data.

**Comment by chrusher** [comment]
The backfiller already has a `--start` option which can be used to limit backfills to the last N hours or to after a datetime.

It should be easy to add the option to delete data older than M hours ago to the backfiller.
