### ISSUE TITLE
Change Restreamer default port

### ISSUE THREAD

**Issue by MasterGunner** [ekimekim/wubloader#16]
Could we change the default port the Restreamer listens on to one of the following (or make it settable):
80
8080
8880
2052
2082
2086
2095

If it's on one of those ports, I can proxy it through Cloudflare for HTTPS, which makes testing and debugging easier.

**Comment by ekimekim** [comment]
It is settable with the --port option (put it at the end of your docker run)

**Comment by MasterGunner** [comment]
Admittedly I am very unfamiliar with Flask, but it looks like it's hard-coded here: https://github.com/ekimekim/wubloader/blob/master/restreamer/restreamer/main.py#L166

**Comment by ekimekim** [comment]
The `port=8000` arg defines a command line option, due to our use of argh.
This is the same way base_dir is set. Run with --help for a list of options.

**Comment by MasterGunner** [comment]
Ah, thanks. Python is weird.
