### ISSUE TITLE
Thrimbletrimmer video player suggestions

### ISSUE THREAD

**Issue by chrusher** [ekimekim/wubloader#161]
These are long term goals for someone who is a JavaScript wizard:

Show tenths of a second (or smaller amount) in the start and end times of the trim.

A visual display of the audio levels.

**Comment by chrusher** [comment]
The show fraction of a second suggestion is now in #168

**Comment by ekimekim** [comment]
Split out the other half into https://github.com/ekimekim/wubloader/issues/216, every item here now has its own issue.
