### ISSUE TITLE
Add support for custom tags

### ISSUE THREAD

**Issue by chrusher** [ekimekim/wubloader#169]
Currently the tags given a uploaded video are an event's category and sheet_name.

Going forward there will be a tag column in the sheet and tags should be editable in Thrimbletrimmer.

Non-exhaustive list of changes need to implement:

**postgres**

- Add `sheet_tags` and `edit_tags` columns to the event. We need two columns to keep things idempotent. 

**sheetsync**

- Read the tags in the tag column of the sheet into `sheet_tags`

**thrimshim**

- Handle updating the `edit_tags` column.
- Provide a list of existing tags.

**cutter**

- Include the `edit_tags` in the tags passed to the upload backends.

**Thrimbletrimmer**

- Display what tags are auto added to video
- Notify when a tag has not been used before

**Comment by chrusher** [comment]
Do we want to keep hard coding the inclusion of the sheet_name and category tags?

**Comment by ekimekim** [comment]
I think so, yes. Having to manually add them each time would be error prone.
We could make them semi-manual by automatically adding them to sheet tags (ie. so the editor could then change them), but I don't think there's any situation where we don't want those tags.

**Comment by ekimekim** [comment]
For parsing from sheet, format is comma-seperated and leading/trailing whitespace stripped. eg. `foo, bar,baz,  ab cd e , f ` would parse to `["foo" ,"bar", "baz", "ab cd e", "f"]`.
