### ISSUE TITLE
Playlist Manager

### ISSUE THREAD

**Issue by ekimekim** [ekimekim/wubloader#179]
This year, youtube removed support for automatically populating playlists based on video tags.
We have many playlists and it is a chore to manage manually. So, we want to automate this.

This will take the form of a new component which watches for new videos in the DB, and adds them to playlists
based on their tags as listed in the DB. The mapping of playlist IDs to tags is static config. To avoid race conditions we should ensure only one playlist manager is running at once.
Note that we should do the right thing if we are restarted mid-run with a new playlist in the config, ie. it should find all previous videos and insert them then.

We need to be careful however, as adding to a playlist is a relatively expensive operation (50 quota, 1/32nd of uploading a video).
The good news is that operation includes inserting the video at any point in the playlist, so we can maintain correct order by inserting at the correct position every time. "Correct position" is done by event start time after mapping video ids back to events. We ignore unrecognized video ids (assumedly these were added manually) and insert after them on a tie (to prevent them getting "stuck" at the end of the playlist).

There is another quota issue. Listing playlist contents is meant to be cheap (1 quota), but each query only returns at most 50 items. We have some 1000-item playlists which can add up quickly.
We optimize to avoid unnessecary large reads by maintaining a mirrored copy of the playlist state locally. We validate this against the actual playlist by reading only one page and comparing the total playlist size (we assume manual changes will only ever be additions). This may turn out to be unnessecary if subsequent query pages do not count for quota - we need to test this.

A potential gotcha here: Previously we had several hard-coded tags added at upload time. For this to work properly all tags should be in the tags field. Default tags should instead be added at sheetsync. Make sure poster moment also creates an implicit tag.

**Comment by chrusher** [comment]
Looks good to me.
