### ISSUE TITLE
Twitch "stream is down" stream

### ISSUE THREAD

**Issue by chrusher** [ekimekim/wubloader#214]
Twitch can show a "stream is down" placeholder stream if the stream goes down. 

https://help.twitch.tv/s/article/Disconnect-Protection?language=en_US

We need to investigate if and how this effects the wubloader and if it does impact the wubloader, develop a work around.

**Comment by ekimekim** [comment]
from a HLS perspective, what happens is:
the segment the broadcaster was in the middle of sending ends mid-way
a new segment starts with different encoding settings (in my test, it was 1080p even though my own stream was 720p) showing the error screen
then the error screen content continues as normal from there until the stream comes back and the reverse happens
this shouldn't cause us any issues. from the wubloader perspective, it's all legitimate content
it's just that the error screen will end up in our canonical record of "what was streamed"
the only sticking point may be the encoding differences. fast cuts aren't proved to behave correctly across a change in encoding like that. I think it'd work fine but would want to double check if we end up cutting a video which starts or ends at a stream drop
i'm like 80% sure things will just work even in that case, and in the worst case we just need to cut around it, so i'm calling this "everything is fine".
