### ISSUE TITLE
Port codebase to python 3

### ISSUE THREAD

**Issue by ekimekim** [ekimekim/wubloader#221]
Unfortunately we've reached a point where staying on python 2 is no longer a workable option. Our builds are fragile and our libraries buggy because upstream doesn't even bother to test python 2 compatability anymore. Most libraries are frozen at old versions.

We will need to be careful with our 2 -> 3 port as we work with binary data fairly often. Thankfully most of this binary data such as filenames are in a context where we can assume ascii only, so converting them to unicode is fine - we don't need to support non-utf-8 filepaths. Segment data will be truly binary though, and working with binary files around `subprocess.Popen` may be painful.

It would be nice if we could approach this issue piecemeal, but due to the `common` library that's not really doable. We would need to maintain a cross-compatible common, or else two copies, in order to work with some components in py2 and some in py3. In practice, it will be simpler to do a hard switch then test and deal with breakage - thankfully we don't need to worry about uptime outside of the run, so we have plenty of time.

**Comment by chrusher** [comment]
Is it smarter to do the port now before we do anything else on the wubloader?
