### ISSUE TITLE
restreamer may fail to shut down if SIGTERM delivered during startup

### ISSUE THREAD

**Issue by ekimekim** [ekimekim/wubloader#226]
This is a race between when we install the SIGTERM handler, and calling `server.serve_forever()`.
In this case `server.stop()` is called before `server.serve_forever()`, and this has the effect of
the `stop()` being ignored.

Interestingly thrimshim already has a workaround for this, but it's a bit hacky.
I think something better would be along the lines of (pseudocode):

```
stopping = gevent.Event()
on sigterm:
	stopping.set()
serve = gevent.spawn(server.serve_forever)
gevent.wait([serve, stopping], count=1) # wait for either
server.stop()
serve.get() # re-raise if serve_forever() errored
```

**Comment by HeNine** [comment]
How about:

```python
    stopping = gevent.event.Event()

    def stop():
        logging.info("Shutting down")
        stopping.set()
        server.stop()

    gevent.signal_handler(signal.SIGTERM, stop)

    if not stopping.is_set():
        logging.info('Starting up')
        server.serve_forever()
```

**Comment by ekimekim** [comment]
Still vulnerable to the race if the signal arrives in between `if not stopping.is_set()` and `server.serve_forever()`. Or rather, in between the code within `stopping.is_set` that checks the state, and the code within server.serve_forever that sets the state such that server.stop actually works.

The idea behind the code I posted is that it no longer matters whether server.serve_forever is called or not, as the only thing that matters is whether stopping is set.

**Comment by HeNine** [comment]
I actually tested it and it's a whole shitshow of greenlet scheduling.

**Comment by ekimekim** [comment]
This turned out to be way simpler than I thought. The server object has a `.start()` method which completes startup then returns - in fact `serve_forever()` is implemented as a `start()` followed by a wait for stop.
All we need to do is ensure `start()` is called and fully completed, then wait on our stopping event ourselves:

```
stopping = gevent.event.Event()
on SIGTERM:
  stopping.set()
server.start()
stopping.wait()
server.stop()
```

`server.stop()` will block until all handlers are complete.
