### ISSUE TITLE
Custom thumbnails for videos

### ISSUE THREAD

**Issue by ElementalAlchemist** [ekimekim/wubloader#259]
Apparently it's come up a few times this year that we've wanted videos to have custom thumbnails.

This will require both Thrimbletrimmer and backend dev.

**Comment by ekimekim** [comment]
From #273:

Min viable: Ability to upload thumbnail image on edit

Bonus:

    Pick between custom or a frame from the video (bonus bonus: pick the frame)
    For generated from frame, use a shift-specific template

**Comment by ElementalAlchemist** [comment]
With the merging of #297, this all got done (including all the bonus stuff listed here). If we have further enhancements (or issues with it), we can put those in their own spots.
