### ISSUE TITLE
handle deleting segments

### ISSUE THREAD

**Issue by ekimekim** [ekimekim/wubloader#272]
need a tombstoning thing

**Comment by chrusher** [comment]
The simplest implementation this I can think of is the database having a list of segments to ignore when backfilling from other nodes and also to delete if already present. The backfiller already has code to delete old hours.

**Comment by ekimekim** [comment]
I'd rather not involve the database - right now the only thing the backfiller uses the DB for is service discovery, which is useful but not vital. I'd like to be able to continue to run backfiller without a database if needed.

Instead I'd like to do this at the segment filesystem layer. Add logic such that if there exists an empty file `NAME.tombstone`, it prevents a file named `NAME.ts` from being backfilled, or used when listing segments. These tombstones would be ignored when listing segments, but would be propogated by backfiller. We would still require a manual delete of the original data, for safety.
This tombstoning approach is common in distributed systems and should suit our purposes well.

**Comment by chrusher** [comment]
Ok that does not sound too hard to do. I guess the only trick is trying to avoid situations where you get a segment before you get its tombstone.

**Comment by ekimekim** [comment]
Since they're in the same hour they should always be fetched at the same time - we'll just need to ensure that we scan the result for tombstones before starting any downloads.

**Comment by chrusher** [comment]
The three places we are listing segments is in `common.segments`, `restreamer` and `backfiller` right?

**Comment by ekimekim** [comment]
I also found places in downloader and segment_coverage.
