### ISSUE TITLE
thrimbletrimmer: Show how youtube title will be shortened

### ISSUE THREAD

**Issue by ekimekim** [ekimekim/wubloader#282]
In many contexts on youtube, the full video title is not shown. Instead the first ~30 characters are, with a `...` indicating more. Showing how this will display in thrimbletrimmer may encourage editors to think about how their video title will be seen and ensure they frontload important information.
Example:
* Bad: `DB2021 - The room tries not to laugh as Beej eats the whole thing`
  This gets shortened to `DB2021 - The room tries not...`
* Good: `DB2021 - Beej eats the whole thing as the room tries not to laugh`
  This gets shortened to `DB2021 - Beej eats the whole...`

**Comment by ElementalAlchemist** [comment]
It'd be good to figure out at least some heuristic of how precisely this happens. (precise length? does it always break at a word border?)

**Comment by ElementalAlchemist** [comment]
We looked into this.
As I ended up suspecting, it's CSS-based using pretty much exactly the CSS I was already thinking of/planning to use for ours. (Cool!) It *also* depends on window width (there's some slight variance in the amount of title shown when the window size changes). 200px seems like a reasonable approximation for the space YouTube typically allocates to video titles.
