### ISSUE TITLE
cutter should automatically tag videos

### ISSUE THREAD

**Issue by ekimekim** [ekimekim/wubloader#85]
A set of tags to apply to all videos should be configurable in cutter,
as well as tags based on category and start time (for determining "Day #")

We should also have some canned title and description bits, eg. title = "DBXXXX - {title}" and a description footer.

**Comment by MasterGunner** [comment]
Does the cutter also set monetization? The old Wubloader couldn't because it was using an older version of the API that didn't support it (at least easily).

**Comment by ekimekim** [comment]
Yep, that should be possible. We're using the latest api. Can be another per-location option.

**Comment by ekimekim** [comment]
for reference, tag formats: DB##, DBYYYY, YYYY, Event_Type, "Desert Bus for Hope", "Child's Play Charity", sheet name (ie. day tag)

will need to add sheet name to DB, but that's probably a good idea anyway since it allows you to easily go from db row to sheet location without scanning all sheets for the right id.

**Comment by ekimekim** [comment]
monetization is not possible using the data api. We would need to use the Content ID api, which I don't think we have access to.

https://stackoverflow.com/questions/18800665/how-to-enable-monetization-for-videos-uploaded-with-youtube-data-api-v3
