### ISSUE TITLE
thrimbletrimmer issues and improvements

### ISSUE THREAD

**Issue by chrusher** [ekimekim/wubloader#86]
Since rows in the sheet get stored in the database once they have content and are not removed, any row that has text in it that subsequently gets removed will show up in the thrimbletrimmer dashboard as an empty event. Since rows get text added to them then removed all the time, the thrimblethrimmer dashboard should not display these events (or provide an option to display them).

It maybe useful to be able to sort columns in the dashboard.

It would likely be useful to further filter the unedited events in the dashboard to those marked for editing in the sheet. This would require marked for editing to be stored in the database.

How well does the dashboard handle large number of events? Last year there was about 800 rows in the sheet per day. By the end of the event this would mean the dashboard would be loading and displaying an potentially unwieldy 5000 events.

Does it make sense to have a button in thrimbletrimmer that saves the edit to the database but does not set the state to 'EDITED'?

**Comment by chrusher** [comment]
For seeing videos stuck in the editing queue, it would be useful to see the editing_time. It would also be useful to reload the events from the database without reloading the page so you keep any filters or sorts in place.

**Comment by MasterGunner** [comment]
Summarizing and adding comments:
- Be able to handle a line that was previously populated but later removed.
  - _Should be easy enough to filter out lines without any description. But maybe the database/sheetsync should have a column to indicate that an ID do longer exists/is populated in the database?_
- Sort columns in dashboard
  - _I'm not sure there's really a situation where we want to review events outside of time-order, but also an easy thing to add if you think there's a use case_
- Add filter for which lines are marked for editing.
  - _Absolutely would want to add this, but the database and sheetsync would need to be updated first._
- Handling of large numbers of events (5000+)
  - _Most clients *should* be able to handle the large number of events just fine; and it's easy enough to have a script populate the database until something breaks. However in an ideal world, we'd push the filtering back to the database (via Thrimshim), which is much more efficient. The database/thrimshim would also generate the lists of possible filters._
- A button that in thrimbletrimmer that saves the edit to the database but doesn't set the state to 'Edited'
  - _Like a "Save Draft" button? Probably would be useful; but we'll probably want an explicit "Draft" state column, if only to notify other editors - currently thrimshim would only accept "Edited" and "Unedited" back as State values._
- Add "editing_time" column to the dashboard
  - _Easy enough._
- Keep filters when reloading page/events
  - _Filters are stored in the query string of the URL, so they should be retained when you refresh the page (and your filters can be provided to others as a link)._
- Auto-refresh dashboard
  - _This was actually one of the things I wanted to do; and while it could be as simple as a loop rebuilding the dashboard every minute, that's still kludgy and could interfere with people working. How I'd like to implement it would be via JavaScript Observables, which are ideal for handling time-series data, but are still not well supported without some heavy frameworks on both the front and back ends._

**Comment by MasterGunner** [comment]
So I'd be willing to implement basically everything here on the Dashboard page, but I'd need probably need you or ekim's help for the things that require database/sheetsync changes. The Thrimshim changes I could try my hand at implementing, but you are still more familiar with it if you'd like to take a crack at it.

**Comment by ekimekim** [comment]
I think most of these are nice-to-haves, we don't need to focus on them right now. Especially since people can always use the sheet.

I'd say the only important feature here is Save Draft. This doesn't require a new DB state - if something is UNEDITED but has edit times set, that's totally valid from the DB's perspective. The only question is human confusion, which we can manage via the existing mechanism of the editor column of the sheet, like we already do for preventing two people editing at once.

**Comment by chrusher** [comment]
Yeah, the Save draft is the only one I though we had but didn't. I agree with what Ekim said, these are all nice to haves but none are key.

For sorting by other columns than the start time, the one I can think of is edit time, for looking for videos stuck in cutting.

**Comment by ekimekim** [comment]
I think we've mostly abandoned the idea of the dashboard as a place to browse videos to edit - the sheet fulfills this purpose already perfectly well. Since everything not dashboard-related from this issue has been implemented I'm going to close it.
