### ISSUE TITLE
Sheetsync does not pick up Tech Test/Preshow sheet

### ISSUE THREAD

**Issue by MasterGunner** [ekimekim/wubloader#92]
In my testing, I noticed the sheet sync doesn't pick up the Tech Test & Preshow sheet, since it doesn't fall in the Day 1-7 format.

I'm guessing the simplest way to do it would be to change the worksheets array in the docker compose to an arbitrary list of sheet names instead of a generated one in a specific format; or have two arrays (one generated, one arbitrary) that get joined together.

**Comment by ekimekim** [comment]
This is a pretty simple config issue, just need to add it to the top of `docker-compose.jsonnet` as an addition to the existing `Day N` list.
