### ISSUE TITLE
Metrics around segment coverage

### ISSUE THREAD

**Issue by ekimekim** [ekimekim/wubloader#95]
This could be part of restreamer or its own service. It should periodically scan each hour and compile some metrics on how much of the hour is covered by segments, exporting them as gauges in seconds.

It should export:
* Total segment count and segment duration by segment type (full, partial, etc), ie. just sum all the durations without looking for overlap
* Raw coverage by best segment type. This should discard any overlap (eg. one segment from 00:10-00:12 and one segment from 00:11-00:13 would only count as 3 seconds of coverage). Coverage for non-"full" segment types should only cover parts where there's no full segment covering it, ie. the sum of raw coverage over all types should always be <= 1 hour.
* Editable coverage by best segment type. In contrast to raw coverage, editable coverage only counts segments that would be used if we were cutting a video. For example, if we had segments: `00:10-00:12, 00:11-00:13, 00:13-00:15`, then the raw coverage would be 5 seconds (union of all segment time ranges) but the editable coverage would only be 4 seconds (as `get_best_segments()` would first take the `00:10-00:12` segment, then it would discard the `00:11-00:13` segment because it overlaps the current segment, then it would have a 1sec hole before the `00:13-00:15` segment. This is unlikely to occur but if it happens we're going to be very glad we have metrics showing what's going on.
* Total overlapping segment count and overlap duration, by the lesser segment type of each pair (ie. so we can tell the difference between "we have both a full and a partial segment for this time" and "we have two conflicting full segments for this time").
* Count of holes, as determined by editable coverage and raw coverage each. Note we don't need to record total hole duration as that is implied by subtracting coverage from an hour.

**Comment by chrusher** [comment]
The hole duration will not be the difference between an hour and the coverage length for the first and last hour. Admittedly it's hard to tell whether the first and last segments are actually when the stream started and finished respectively (the issue of being complete to present is easy).

I'm not sure how easy this is to integrate with Prometheus but a cool way to visualise the coverage would be to have each hour represented by a 60 by 60 pixel image where each pixel represents a second. The pixels could then be colour coded by whether we have full, partial or no coverage for that second. This is something I could easily do using `numpy` and `matplotlib` I use to make plots everyday at work.

**Comment by ekimekim** [comment]
Ooh, I like that idea. Can you make an endpoint in the restreamer that generates the image? Then we can link to it directly from the dashboard so it shows up with the other graphs: https://community.grafana.com/t/add-graphic-to-the-dashboard/2231

**Comment by chrusher** [comment]
Sure. My idea was to generate the images when the coverage was calculated then save them somewhere where flask or ngnix can serve them.

**Comment by ekimekim** [comment]
that's probably a better idea. coverage calculations might take a while.

**Comment by chrusher** [comment]
I have a prototype working now. It's relatively fast - 0.2 seconds to check a full hour of 2 s segments and generate an image for that hour on my MacBook (though this might be due to the SSD enabling fast IO).

In terms of serving the images, the simplest way would be to put them in the same directory as the segments are stored in since it is already served by ngnix (and stored externally to the container). Care would have to be taken that the images are not mistook as segments by other components.

Currently the images are saved individual for each hour with no labels or titles in the images, assuming that the monitoring dashboard will handle the layout and labels. I could easily have the code generate images with multiple hours in them (or a single image with all the hours), with all the hours labelled and in a grid.

**Comment by ekimekim** [comment]
The dashboard doesn't have very good support for this, it's only really going to be able to show a static URL, or at best one templated with `channel` and `quality`. So you should make one image per (channel, quality) and show the entire timescale on it.

We can probably condense it to 2 seconds per pixel since that's segment length anyway. Then if you have each 10-minute section be a 300-pixel tall column, the entire image would be ~1000px wide by the end of the run, and that's about the same size (1000x300 ish) as a row on a dashboard.

**Comment by chrusher** [comment]
Here are some images I created using made up data for 160 hours:
![test_blue_orange](https://user-images.githubusercontent.com/105709/67056221-088be700-f143-11e9-8380-161956e4d613.png)
![test_green_red](https://user-images.githubusercontent.com/105709/67056222-088be700-f143-11e9-84c2-6b989e3e2101.png)
Blue or green are times with full coverage, orange or red are covered by partial segments and white is missing data. Green and red are the colours we normally think of for good and bad but the blue and orange have better contrast. Given that you are potentially trying to pick up single pixels, you want colours that pop.

**Comment by ekimekim** [comment]
ooh, nice. And I agree, let's go with the blue/white/orange.
